completed query and update animals table
huzaifakhan0308/vet_clinic pull request #2
Opened 2023-03-28 22:51 UTC by huzaifakhan0308

> Vet clinic database

- Use database transactions.
- Modify and delete data in SQL.
- complex queries that answer analytical questions.

Inside a transaction update the animal's table by setting the species column to unspecified
![Screenshot 2023-03-29 014318](https://user-images.githubusercontent.com/114409312/228382945-da78df4b-c1c4-4349-8557-9d774599883b.png)
![Screenshot 2023-03-29 014851](https://user-images.githubusercontent.com/114409312/228383081-dce27ce2-cdaf-4e7b-ac33-f1bc54149870.png)

Update the animal's table by setting the species column to digimon for all animals that have a name ending in mon
Update the animal's table by setting the species column to pokemon for all animals that don't have species already set
![Screenshot 2023-03-29 020412](https://user-images.githubusercontent.com/114409312/228383298-4df49ca4-5e61-4d95-95ee-bb6ad543ddd0.png)
![Screenshot 2023-03-29 020600](https://user-images.githubusercontent.com/114409312/228383403-2be50730-7235-448d-8d12-c31541ea7706.png)

Inside a transaction delete all records in the animal's table, then roll back the transaction.
After the rollback verify if all records in the animal's table still exist.
![Screenshot 2023-03-29 020932](https://user-images.githubusercontent.com/114409312/228383504-810bed6b-975a-48b4-ae6e-baef8ea0209f.png)
![Screenshot 2023-03-29 021033](https://user-images.githubusercontent.com/114409312/228383538-50066e24-4d89-48a2-b214-156470ac3d9a.png)

Inside a transaction:
- Delete all animals born after Jan 1st, 2022.
- Create a savepoint for the transaction.
- Update all animals' weight to be their weight multiplied by -1.
- Rollback to the savepoint
- Update all animals' weights that are negative to be their weight multiplied by -1.
- Commit transaction
![Screenshot 2023-03-29 021703](https://user-images.githubusercontent.com/114409312/228383936-3c068845-67fc-4df9-a2bf-3334598ebb2a.png)
![Screenshot 2023-03-29 022746](https://user-images.githubusercontent.com/114409312/228383940-f4656fcb-eb52-43b0-b4f4-8fab1d57f989.png)
![Screenshot 2023-03-29 022844](https://user-images.githubusercontent.com/114409312/228383946-bed77b90-ce4a-429c-92d9-d2d3f4892612.png)

How many animals are there?
![Screenshot 2023-03-29 024421](https://user-images.githubusercontent.com/114409312/228384123-6d22f10f-1f2d-4a4a-9d4b-9a7ceeda550d.png)

How many animals have never tried to escape?
![Screenshot 2023-03-29 024632](https://user-images.githubusercontent.com/114409312/228384152-4dd04dee-29ff-4e4d-bb03-56c6f9e94702.png)

What is the average weight of animals?
![Screenshot 2023-03-29 025050](https://user-images.githubusercontent.com/114409312/228384182-c849aff0-e32f-42d8-ade4-3e3a71430270.png)

Who escapes the most, neutered or not neutered animals?
![Screenshot 2023-03-29 030848](https://user-images.githubusercontent.com/114409312/228384244-6961e1a9-001d-487b-9862-62c3a9876cd5.png)

What is the minimum and maximum weight of each type of animal?
![Screenshot 2023-03-29 031815](https://user-images.githubusercontent.com/114409312/228384283-fa501567-d728-4a01-a3df-2709ef42ac8a.png)

What is the average number of escape attempts per animal type of those born between 1990 and 2000?
![Screenshot 2023-03-29 033016](https://user-images.githubusercontent.com/114409312/228384336-c594da64-5678-4de0-9c7e-e59e8c973092.png)

2023-03-28 22:56 UTC, rloterh reviewed
Hi Huzaifa, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

Kindly ensure that your ReadMe is professionally documented, and adhere(s) to the following standard(s):
- [ ] Kindly ensure that provided placeholder texts/ guide instructions are removed and/or replaced with appropriate contents applicable under each section of your ReadMe.
- [ ] All main headers from the [ReadMe template](https://github.com/microverseinc/readme-template) should be present in your ReadMe, only the _FAQ_ section is optional.
- [ ]  The _Future Features_ section of your ReadMe includes 1-3 potential features to be added later. 
- [ ] Remove Live demo link from the ReadMe if app is not yet deployed.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2023-03-29 09:08 UTC, HAMMAS-SALEEM requested changes
# Required Changes :recycle:
![almost-there](https://user-images.githubusercontent.com/65860678/170491251-b1add8ba-b18f-4648-a893-20e510d957fd.gif)

## Hey @huzaifakhan0308 :wave:

## Highlights :1st_place_medal:

✔️ Descriptive PR Title
✔️ Descriptive PR Summary
✔️ Following Gitflow
✔️ Following some requirements

Good job on implementing some of the requirements, there are some issues that you still need to work on to go to the next project but you are almost there! :blush:

# Optional

_All the changes with optional tags are not crucial enough to prevent you from getting the approval but we highly recommend to students that they should take these changes into consideration._

Cheers and Happy coding! :clap: :clap: :clap:

Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

---------------------------------------

_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-03-29 09:08 UTC, HAMMAS-SALEEM commented on queries.sql
> +ROLLBACK;
- [ ] It would be great if you verify your changes after rollback 😊 to follow your project requirement 👍

**Example for above transaction**

```SQL
   BEGIN; -- start transaction

   UPDATE animals
   SET species = 'unspecified'; -- make change

   SELECT species from animals;
   ROLLBACK;

   SELECT species from animals;

```

2023-03-29 09:08 UTC, HAMMAS-SALEEM commented on queries.sql
> +SELECT * FROM animals
- [ ] You are making transactions but it would be great if begin and commit this transaction to follow the requirements and to make your transaction a TRANSACTION 👍 because in this state it will change the data and will not be called a transaction 🤔
- [ ] Also, it would be great if you verify the changes before and after committing your transaction 👍 to follow the project requirements 😊

**Example for above transaction**

```SQL
   BEGIN;
   UPDATE animals SET species = 'digimon' WHERE name LIKE '%mon'; 
   UPDATE animals SET species = 'pokemon' WHERE species IS NULL; 

   SELECT species from animals;
   COMMIT;
   SELECT species from animals;
```

2023-03-29 09:08 UTC, HAMMAS-SALEEM commented on queries.sql
> +COMMIT;
- [ ] You are making transactions but it would be great if begin this transaction to follow the requirements and to make your transaction a TRANSACTION 👍 because in this state it will change the data and will not rollback anything and be called a transaction 🤔

**Example for above transaction**

```SQL
    BEGIN;

    DELETE FROM animals WHERE  date_of_birth > '2022/01/01' ;
    SAVEPOINT SP1;

    UPDATE animals SET weight_kg = weight_kg * -1; 
    ROLLBACK TO SP1;
    UPDATE animals SET weight_kg = weight_kg * -1 WHERE weight_kg < 0; 

    COMMIT;

```

2023-03-29 09:08 UTC, HAMMAS-SALEEM commented on queries.sql
> +ROLLBACK;
![image](https://user-images.githubusercontent.com/93039359/228480088-6d5248b2-2b4a-48c1-8fe6-a483a1df9ac7.png)

- [ ] It would be nice if you follow the requirements and make the missing transaction from your project requirements 👍

2023-03-29 09:08 UTC, HAMMAS-SALEEM commented on queries.sql
> +SELECT species, AVG(escape_attempts) FROM animals WHERE date_of_birth BETWEEN '1990-01-01' AND '2000-01-01' GROUP BY species;
- [ ] Great work so far but it would be nice if you replace `2000-01-01` with `2000-31-12` because this query wants you to retrieve data between 1990 to 2000, not before 2000 🤔
- [ ] After making all the changes in all the inline comments, kindly add new pictures with latest results in your pull request summary 👍

2023-03-29 09:08 UTC, HAMMAS-SALEEM commented on README.md
**[OPTIONAL]**

- [ ] It is great that you have added the issues page link here 👏 It would be nice if you add a professional comment in this section as well 😊 such as

![image](https://user-images.githubusercontent.com/93039359/228484308-e369acb0-2b5e-4372-8dc1-fc2a735a1014.png)

2023-03-29 09:08 UTC, HAMMAS-SALEEM commented on README.md
![image](https://user-images.githubusercontent.com/93039359/228484549-be40c27a-1a33-4b95-a274-28fad330cae1.png)

**[OPTIONAL]**

- [ ] It would be great if you make all your commit messages capitalize to make your pull request professional 👍

2023-03-29 12:03 UTC, uwadonat approved these changes
## Hi @huzaifakhan0308,

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
### Congratulations! 🎉 
### Highlights
- Correct workflow was used ✔️
- Professional readme file ✔️
- Descriptive pull request message ✔️
![thanks-awesome](https://user-images.githubusercontent.com/65860678/228529528-91240a38-989c-4853-9de6-345c377f24a4.gif)

# Status: Approved ✔️✔️✔️

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100%.
Please, remember to tag me @uwadonat in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
```

2023-03-29 22:00 UTC, merged